### ISSUE TITLE
Why doesn't llama model apply shift like opt?

### ISSUE THREAD

**Issue by HandH1998** [ModelTC/Outlier_Suppression_Plus#7]
Hello, thanks for your great work!
I have a question why the llama doesn't apply `shift` operation like opt. I tried to apply `shift` on llama, but I got worse experiment results on PIQA and WikiText2. I wonder if it is normal. Look forward to your reply. Many thanks!

**Comment by wimh966** [comment]
Hello! This is because that llama does not have the bias. Thus, if the shifting operations is applied, it would slightly increase the flops. To keep all the things same, we do not use shifting on Llama. 
About the performance, I once tried shifting on Llama on 6-bit and 8-bit, but I got slightly better results on PIQA and WikiText2.
